# -*- coding: utf-8 -*-
"""Extend res.partner to cover Salesforce ``Account`` and ``Contact`` objects.

In the Marathon Ventures org, both Accounts (Agencies / TV Networks) and
Contacts (Buyers) are people or companies. Odoo's ``res.partner`` model is
the natural target — we extend it with the Marathon-specific custom fields
rather than creating a duplicate model.
"""

from odoo import api, fields, models


class ResPartner(models.Model):
    _inherit = 'res.partner'

    # Identifies the role this partner plays in the Marathon Ventures
    # business model. A single partner can be flagged with multiple roles
    # (an Agency that is also a Vendor, for example), so we store the
    # primary classification here and use ``is_*`` boolean flags for the rest.
    marathon_role = fields.Selection(
        [
            ('agency', 'Agency'),
            ('advertiser', 'Advertiser'),
            ('network', 'TV Network'),
            ('vendor', 'Vendor'),
            ('buyer', 'Buyer Contact'),
            ('other', 'Other'),
        ],
        string='Marathon Role',
        default='other',
        tracking=True,
    )

    is_agency = fields.Boolean(string='Is Agency')
    is_advertiser = fields.Boolean(string='Is Advertiser')
    is_network = fields.Boolean(string='Is TV Network')
    is_vendor_account = fields.Boolean(string='Is Vendor Account')

    # Salesforce Account custom fields (subset — only the ones used in
    # cross-object relationships and views; the full list of 89 fields is
    # heavily duplicative of standard Odoo partner data such as billing
    # address, phone, etc., which Odoo already covers natively).
    sf_account_id = fields.Char(string='SF Account ID', copy=False)
    account_number = fields.Char(string='Account Number')
    client_code = fields.Char(string='Client Code')
    advertiser_credit_limit = fields.Monetary(
        string='Advertiser Credit Limit',
        currency_field='currency_id',
    )
    intacct_balance = fields.Monetary(
        string='Intacct Balance',
        currency_field='currency_id',
    )
    hold_placed = fields.Boolean(string='Hold Placed on Account')
    cia_required = fields.Boolean(string='CIA (Cash In Advance) Required')
    approved_to_book = fields.Boolean(string='Approved to Book')

    # Buyer / contact custom fields
    buyer_email = fields.Char(string='Buyer Email')
    contact_role = fields.Selection(
        [
            ('buyer', 'Buyer'),
            ('assistant_buyer', 'Assistant Buyer'),
            ('junior_buyer', 'Junior Buyer'),
            ('media_coordinator', 'Media Coordinator'),
            ('planner', 'Planner'),
            ('account_executive', 'Account Executive'),
            ('logs', 'Logs Contact'),
            ('billing', 'Billing'),
            ('other', 'Other'),
        ],
        string='Contact Role',
        help='Per "buyer-contacts-in-sf" SOP: Media Buyers vs Assistant '
             'Buyers vs Coordinators have distinct roles in deal entry.',
    )
    is_buyer_contact_verified = fields.Boolean(
        string='Buyer Contact Verified',
        help='Per training: deal paperwork is often outdated. This flag '
             'indicates the buyer contact email was confirmed against an '
             'up-to-date source before deal entry.',
    )

    # Reverse relations for quick navigation
    deal_ids = fields.One2many(
        'marathon.deal', 'client_account_id', string='Deals'
    )
    advertiser_ids = fields.One2many(
        'marathon.advertiser', 'account_id', string='Linked Advertisers'
    )

    deal_count = fields.Integer(
        string='# Deals', compute='_compute_marathon_counts'
    )

    # =================================================================== #
    # === SF parity fields (auto-generated, full Salesforce field set) === #
    # =================================================================== #
    aa_lc = fields.Date(string="AA LC")
    aa_status = fields.Char(string="AA Status")
    account_id = fields.Many2one('res.partner', string="AccountId", ondelete='set null')
    accu_weather_post_log_week = fields.Date(string="AccuWeather Post Week")
    accu_weather_pre_log_week = fields.Date(string="AccuWeather Prelog Week")
    accu_weather_post_log_url = fields.Char(string="AccuWeather Post Log URL")
    accu_weather_post_logs_date_time = fields.Datetime(string="AccuWeather Post Logs Date/Time")
    accu_weather_pre_logs_date_time = fields.Datetime(string="AccuWeather Pre Logs Date/Time")
    accu_weather_prelog_1a_url = fields.Char(string="AccuWeather Prelog 1a URL")
    accu_weather_prelog_url = fields.Char(string="AccuWeather Prelog URL")
    accu_weather_query_postlogs = fields.Char(string="AccuWeather Query Postlogs")
    accu_weather_query_prelogs_nw = fields.Char(string="AccuWeather Query Prelogs NW")
    accu_weather_query_prelogs = fields.Char(string="AccuWeather Query Prelogs")
    agency_status = fields.Char(string="Agency Status")
    antenna_tv_post_week = fields.Date(string="AntennaTV Post Week")
    antenna_tv_pre_log_week = fields.Date(string="AntennaTV PreLog Week")
    assistant_name = fields.Char(string="AssistantName")
    assistant_phone = fields.Char(string="AssistantPhone")
    bl_lc = fields.Date(string="BL LC")
    bl_status = fields.Char(string="BL Status")
    btt_missing_video_url = fields.Char(string="BTT Missing Video URL")
    btt_pp_postlog_week = fields.Date(string="BTT PP Postlog Week")
    btt_postlog_url = fields.Char(string="BTT Postlog URL")
    busted_post_log_week = fields.Date(string="BUSTEDPostLogWeek")
    busted_pre_log_week = fields.Date(string="BUSTED PreLog Week")
    busted_post_log_url = fields.Char(string="BUSTED Post Log URL")
    busted_post_logs_date_time = fields.Datetime(string="BUSTED Post Logs Date Time")
    busted_pre_logs_date = fields.Datetime(string="BUSTED Pre Logs Date")
    busted_prelog_nw_url = fields.Char(string="BUSTED Prelog NW URL")
    birthdate = fields.Char(string="Birthdate")
    blue_ae = fields.Many2one('res.users', string="Blue AE", ondelete='set null')
    bounce_tv_query_postlogs = fields.Char(string="BounceTV Query Postlogs")
    bounce_tv_query_prelogs_nw = fields.Char(string="BounceTV Query Prelogs NW")
    bounce_tv_query_prelogs = fields.Char(string="BounceTV Query Prelogs")
    bounce_post_log_url = fields.Char(string="Bounce Post Log URL")
    bounce_post_logs_date_time = fields.Datetime(string="Bounce Post Logs Date/Time")
    bounce_post_week = fields.Date(string="Bounce Post Week")
    bounce_pre_logs_date_time = fields.Datetime(string="Bounce Pre Logs Date/Time")
    bounce_prelog_1a_url = fields.Char(string="Bounce Prelog 1a URL")
    bounce_prelog_url = fields.Char(string="Bounce Prelog URL")
    bounce_prelog_week = fields.Date(string="Bounce Prelog Week")
    busted_prelog_url = fields.Char(string="Busted Prelog URL")
    buyer_attributes = fields.Char(string="BuyerAttributes")
    cj_lc = fields.Date(string="CJ LC")
    cj_status = fields.Char(string="CJ Status")
    cl_lc = fields.Date(string="CL LC")
    cl_status = fields.Char(string="CL Status")
    call_cycle = fields.Selection([('30', '30'), ('60', '60'), ('90', '90'), ('Fallow', 'Fallow')], string="Call Cycle")
    can_allow_portal_self_reg = fields.Char(string="CanAllowPortalSelfReg")
    confess_post_log_week = fields.Date(string="ConfessPostLogWeek")
    confess_pre_log_week = fields.Date(string="ConfessPreLogWeek")
    confess_post_logs_date_time = fields.Datetime(string="Confess Post Logs Date Time")
    confess_postlog_url = fields.Char(string="Confess Postlog URL")
    confess_pre_log_date_time = fields.Datetime(string="Confess Pre Log Date/Time")
    confess_prelog_nw_url = fields.Char(string="Confess Prelog NW URL")
    confess_prelog_url = fields.Char(string="Confess Prelog URL")
    contact_source = fields.Char(string="ContactSource")
    court_tv_post_log_week = fields.Date(string="CourtTV PostLogWeek")
    court_tv_pre_log_week = fields.Date(string="CourtTV Prelog Week")
    court_tv_post_logs_date_time = fields.Datetime(string="CourtTV Post Logs Date/Time")
    court_tv_post_log_url = fields.Char(string="CourtTV Post-log URL")
    court_tv_pre_logs_date_time = fields.Datetime(string="CourtTV Pre Logs Date/Time")
    court_tv_prelog_nw_url = fields.Char(string="CourtTV Prelog NW URL")
    court_tv_prelog_url = fields.Char(string="CourtTV Prelog URL")
    court_tv_query_postlogs = fields.Char(string="CourtTV Query Postlogs")
    court_tv_query_prelogs_nw = fields.Char(string="CourtTV Query Prelogs NW")
    court_tv_query_prelogs = fields.Char(string="CourtTV Query Prelogs")
    defy_scripps_post_log_week = fields.Date(string="DEFY Scripps Post Log Week")
    defy_scripps_pre_log_week = fields.Date(string="DEFY Scripps PreLog Week")
    defy_ftv_post_log_week = fields.Date(string="Defy FTV PostLog Week")
    defy_ftv_pre_log_week = fields.Date(string="Defy FTV PreLog Week")
    defy_scripps_prelog_date_time = fields.Datetime(string="Defy Scripps Prelog DateTime")
    defy_ftv_post_logs_date_time = fields.Datetime(string="Defy FTV Post Logs Date/Time")
    defy_ftv_pre_log_date_time = fields.Datetime(string="Defy FTV Pre Log Date/Time")
    defy_ftv_query_postlogs = fields.Char(string="Defy FTV Query Postlogs")
    defy_ftv_query_prelogs_nw = fields.Char(string="Defy FTV Query Prelogs NW")
    defy_ftv_query_prelogs = fields.Char(string="Defy FTV Query Prelogs")
    defy_scripps_post_log_url = fields.Char(string="Defy Scripps Post Log URL")
    defy_scripps_post_logs_date_time = fields.Datetime(string="Defy Scripps Post Logs DateTime")
    defy_scripps_prelog_nw_url = fields.Char(string="Defy Scripps Prelog NW URL")
    defy_scripps_prelog_url = fields.Char(string="Defy Scripps Prelog URL")
    defy_scripps_query_post_logs = fields.Char(string="Defy Scripps Query Post Logs")
    defy_scripps_query_pre_logs_nw = fields.Char(string="Defy Scripps Query Pre Logs NW")
    defy_scripps_query_pre_logs = fields.Char(string="Defy Scripps Query Pre Logs")
    department = fields.Char(string="Department")
    department_group = fields.Char(string="DepartmentGroup")
    digital_postlog_url = fields.Char(string="Digital Postlog URL")
    digital_postlog_week = fields.Date(string="Digital Postlog Week")
    disney_post_log_week = fields.Date(string="Disney Post Log Week")
    disney_postlog_url = fields.Char(string="Disney Postlog URL")
    disney_prelog_nw_url = fields.Char(string="Disney Prelog NW URL")
    disney_prelog_url = fields.Char(string="Disney Prelog URL")
    disney_prelog_week = fields.Date(string="Disney Prelog Week")
    do_not_call = fields.Char(string="DoNotCall")
    duplicate_approval = fields.Selection([('Approved', 'Approved'), ('Not Approved', 'Not Approved')], string="Duplicate Approval")
    eo_lc = fields.Date(string="EO LC")
    eo_status = fields.Char(string="EO Status")
    email_logs = fields.Boolean(string="Email Logs", default=False)
    emerald_ae = fields.Many2one('res.users', string="Emerald AE", ondelete='set null')
    fallow_date = fields.Date(string="Fallow Date")
    fire_ae_bounce = fields.Many2one('res.users', string="Fire AE", ondelete='set null')
    fire_ae_escape = fields.Many2one('res.users', string="Wolf AE", ondelete='set null')
    fox_postlog_url = fields.Char(string="Fox Postlog URL")
    fox_postlog_week = fields.Date(string="Fox Postlog Week")
    fox_prelog_nw_url = fields.Char(string="Fox Prelog NW URL")
    fox_prelog_week = fields.Date(string="Fox Prelog Week")
    fox_synd_prelog_url = fields.Char(string="Fox Synd Prelog URL")
    gc_lc = fields.Date(string="GC LC")
    gc_status = fields.Char(string="GC Status")
    gender_identity = fields.Char(string="GenderIdentity")
    green_ae = fields.Many2one('res.users', string="Green AE", ondelete='set null')
    green_incumbency_sheet_url = fields.Char(string="Green Incumbency Sheet URL")
    grit_tv_post_log_week = fields.Date(string="GritTV PostLog Week")
    grit_tv_pre_log_week = fields.Date(string="GritTV PreLog Week")
    grit_tv_post_logs_date_time = fields.Datetime(string="GritTV Post Logs Date/Time")
    grit_tv_post_log_url = fields.Char(string="GritTV Post-log URL")
    grit_tv_pre_logs_date_time = fields.Datetime(string="GritTV Pre Logs Date/Time")
    grit_tv_query_postlogs = fields.Char(string="GritTV Query Postlogs")
    grit_tv_query_prelogs_nw = fields.Char(string="GritTV Query Prelogs NW")
    grit_tv_query_prelogs = fields.Char(string="GritTV Query Prelogs")
    grit_pp_postlog_url = fields.Char(string="Grit PP Postlog URL")
    grit_pp_postlog_week = fields.Date(string="Grit PP Postlog Week")
    grit_pp_query_postlogs = fields.Char(string="Grit PP Query Postlogs")
    grit_prelog_1a_url = fields.Char(string="Grit Prelog NW URL")
    grit_prelog_url = fields.Char(string="Grit Prelog URL")
    has_opted_out_of_email = fields.Char(string="HasOptedOutOfEmail")
    has_opted_out_of_fax = fields.Char(string="HasOptedOutOfFax")
    hemisphere_pp_post_logs = fields.Date(string="Hemisphere PP Post Logs")
    hemisphere_pp_postlog_week = fields.Date(string="Hemisphere PP Postlog Week")
    hemisphere_pp_pre_log_week = fields.Date(string="Hemisphere PP PreLog Week")
    hemisphere_pp_pre_nw_url = fields.Char(string="Hemisphere PP Pre NW URL")
    hemisphere_pp_pre_tw_url = fields.Char(string="Hemisphere PP Pre TW URL")
    hemisphere_paid_programing_post_logs = fields.Char(string="Hemisphere Paid Programing Post Logs")
    hemisphere_pre_log_week = fields.Date(string="Hemisphere PreLog Week")
    hemisphere_sf_prelog_tw_url = fields.Char(string="Hemisphere SF Prelog tw url")
    hemisphere_short_form_post_log_week = fields.Date(string="Hemisphere Short Form Post Log Week")
    hemisphere_short_form_postlog = fields.Char(string="Hemisphere Short Form Postlog")
    hemisphere_short_form_pre_nw_url = fields.Char(string="Hemisphere Short Form Pre NW URL")
    hemisphere_short_form_pre_tw_url = fields.Char(string="Hemisphere Short Form Pre TW URL")
    hemisphere_short_form_prelog_date_time = fields.Datetime(string="Hemisphere Short Form Prelog Date/Time")
    hemisphere_short_form_prelog_week = fields.Date(string="Hemisphere Short Form Prelog Week")
    home_phone = fields.Char(string="HomePhone")
    ion_mystery_post_log_week = fields.Date(string="ION Mystery PostLog Week")
    ion_mystery_pre_log_week = fields.Date(string="ION Mystery PreLog Week")
    ion_plus_post_log_week = fields.Date(string="IONPlusPostLogWeek")
    ion_plus_pre_log_week = fields.Date(string="ION Plus PreLog Week")
    ion_television_post_log_week = fields.Date(string="ION Postlog Week")
    ion_television_pre_log_week = fields.Date(string="ION Television Prelog Week")
    ion_mystery_post_logs_date_time = fields.Datetime(string="ION Mystery Post Logs Date/Time")
    ion_mystery_post_log_url = fields.Char(string="ION Mystery Post-log URL")
    ion_mystery_pre_logs_date_time = fields.Datetime(string="ION Mystery Pre Logs Date/Time")
    ion_mystery_prelog_1a_url = fields.Char(string="ION Mystery Prelog 1a URL")
    ion_mystery_prelog_url = fields.Char(string="ION Mystery Prelog URL")
    ion_mystery_query_post_logs = fields.Char(string="ION Mystery Query PostLogs")
    ion_mystery_query_prelogs_nw = fields.Char(string="ION Mystery Query Prelogs NW")
    ion_mystery_query_prelogs = fields.Char(string="ION Mystery Query Prelogs")
    ion_pp_query_postlogs = fields.Char(string="ION PP Query Postlogs")
    ion_plus_post_logs_date_time = fields.Datetime(string="ION Plus Post Logs Date/Time")
    ion_plus_pre_log_date_time = fields.Datetime(string="ION Plus Pre Log Date/Time")
    ion_plus_query_postlogs = fields.Char(string="ION Plus Query Postlogs")
    ion_plus_query_prelogs_nw = fields.Char(string="ION Plus Query Prelogs NW")
    ion_plus_query_prelogs = fields.Char(string="ION Plus Query Prelogs")
    ion_post_logs_date_time = fields.Datetime(string="ION Post Logs Date/Time")
    ion_pre_log_date_time = fields.Datetime(string="ION Pre Log Date/Time")
    ion_pre_logs_nw = fields.Char(string="ION Query Prelogs NW")
    ion_query_postlogs = fields.Char(string="ION Query Postlogs")
    ion_query_prelogs = fields.Char(string="ION Query Prelogs")
    io_campaign = fields.Char(string="IO Campaign")
    io_end = fields.Date(string="IO End")
    io_start = fields.Date(string="IO Start")
    incumbency_month = fields.Date(string="Green Incumbency Month")
    individual_id = fields.Many2one('res.partner', string="IndividualId", ondelete='set null')
    ion_pp_post_log_url = fields.Char(string="Ion PP Post Log Url")
    ion_pp_postlog_week = fields.Date(string="Ion PP Postlog Week")
    jf_lc = fields.Date(string="JF LC")
    jf_status = fields.Char(string="JF Status")
    jade_ae = fields.Many2one('res.users', string="Jade AE", ondelete='set null')
    jigsaw = fields.Char(string="Jigsaw")
    kw_lc = fields.Date(string="KW LC")
    kw_status = fields.Char(string="KW Status")
    kiy_test_lightning_conductor = fields.Char(string="Kiy test Lightning Conductor")
    lf_current_month = fields.Char(string="LF Current Month")
    lf_month = fields.Char(string="LF Month")
    lf = fields.Boolean(string="LF", default=False)
    laff_post_log_week = fields.Date(string="Laff PostLog Week")
    laff_pre_log_week = fields.Date(string="Laff PreLog Week")
    laff_pp_post_log_url = fields.Char(string="Laff PP Post Log Url")
    laff_pp_postlog_week = fields.Date(string="Laff PP Postlog Week")
    laff_pp_query_postlogs = fields.Char(string="Laff PP Query Postlogs")
    laff_post_log_url = fields.Char(string="Laff Post Log URL")
    laff_post_logs_date_time = fields.Datetime(string="Laff Post Logs Date/Time")
    laff_pre_logs_date_time = fields.Datetime(string="Laff Pre Logs Date/Time")
    laff_prelog_1_a_url = fields.Char(string="Laff Prelog NW URL")
    laff_prelog_url = fields.Char(string="Laff Prelog URL")
    laff_query_postlogs = fields.Char(string="Laff Query Postlogs")
    laff_query_prelogs_nw = fields.Char(string="Laff Query Prelogs NW")
    laff_query_prelogs = fields.Char(string="Laff Query Prelogs")
    last_cu_request_date = fields.Char(string="LastCURequestDate")
    last_cu_update_date = fields.Char(string="LastCUUpdateDate")
    last_contact = fields.Date(string="LastContact")
    last_contact_activity = fields.Datetime(string="Last Contact Activity")
    lead_source = fields.Char(string="LeadSource")
    lead_type = fields.Selection([('Active', 'Active'), ('Target', 'Target'), ('Fallow', 'Fallow'), ('Not Target', 'Not Target')], string="Lead Type")
    lime_ae = fields.Many2one('res.users', string="Lime AE", ondelete='set null')
    logs_cc = fields.Char(string="Logs CC")
    logs_contact = fields.Many2one('res.partner', string="Logs Contact", ondelete='set null')
    mlb_apple_tv_pre_log_week = fields.Date(string="MLBAppleTVPreLog Week")
    mlb_apple_tv_post_logs_date_time = fields.Datetime(string="MLBAppleTV Post Logs Date/Time")
    mlb_apple_tv_post_week = fields.Date(string="MLBAppleTV Post Week")
    mlb_apple_tv_postlog_url = fields.Char(string="MLBAppleTV Postlog URL")
    mlb_apple_tv_prelog_url = fields.Char(string="MLBAppleTV Prelog URL")
    mlb_apple_tv_prelogs_date_time = fields.Datetime(string="MLBAppleTV Prelogs Date/Time")
    mlb_apple_tv_query_postlogs = fields.Char(string="MLBAppleTV Query Postlogs")
    mlb_apple_tv_query_prelogs_nw = fields.Char(string="MLBAppleTV Query Prelogs NW")
    mlb_apple_tv_query_prelogs = fields.Char(string="MLBAppleTV Query Prelogs")
    mlb_ae = fields.Many2one('res.users', string="MLB AE", ondelete='set null')
    mlb_apple_tv_prelog_nw_url = fields.Char(string="MLB AppleTV Prelog NW URL")
    mlb_network_pre_logs_date_time = fields.Datetime(string="MLB Network Pre Logs Date/Time")
    mlb_network_prelog_1_a_url = fields.Char(string="MLB Network Prelog NW URL")
    mlb_network_prelog_url = fields.Char(string="MLB Network Prelog URL")
    mlb_post_log_url1 = fields.Char(string="MLB Post Log URL")
    mlb_post_log_week = fields.Date(string="MLB Post Week")
    mlb_post_logs_date_time = fields.Datetime(string="MLB Post Logs Date/Time")
    mlb_pre_log_week = fields.Date(string="MLB PreLog Week")
    mlb_query_postlogs = fields.Char(string="MLB Query Postlogs")
    mlb_query_prelogs_nw = fields.Char(string="MLB Query Prelogs NW")
    mlb_query_prelogs = fields.Char(string="MLB Query Prelogs")
    mp_lc = fields.Date(string="MP LC")
    mp_status = fields.Char(string="MP Status")
    mailing_address = fields.Char(string="MailingAddress")
    maple_ae = fields.Many2one('res.users', string="Maple AE", ondelete='set null')
    merit_street_media_post_log_week = fields.Date(string="Merit Street Post Week")
    merit_street_media_pre_log_week = fields.Date(string="Merit Street Media PreLog Week")
    merit_street_media_pre_logs_date_time = fields.Datetime(string="Merit Street Media Pre Logs Date/Time")
    merit_street_post_logs_date_time = fields.Datetime(string="Merit Street Post Logs Date/Time")
    merit_street_postlog_url = fields.Char(string="Merit Street Postlog URL")
    merit_street_prelog_nw_url = fields.Char(string="Merit Street Prelog NW URL")
    merit_street_prelog_url = fields.Char(string="Merit Street Prelog URL")
    merit_street_query_postlog = fields.Char(string="Merit Street Query Postlog")
    merit_street_query_prelog_nw = fields.Char(string="Merit Street Query Prelogs NW")
    merit_street_query_prelog = fields.Char(string="Merit Street Query Prelog")
    mobile_phone = fields.Char(string="MobilePhone")
    nbcu_s_postlog_week = fields.Date(string="NBCU S Postlog Week")
    nbcu_s_prelog_week = fields.Date(string="NBCU S Prelog Week")
    nbcu_synd_post_url = fields.Char(string="NBCU Synd Post URL")
    nbcu_synd_prelog_nw_url = fields.Char(string="NBCU Synd Prelog NW URL")
    nbcu_synd_prelog_pd360 = fields.Char(string="NBCU Synd Prelog PD360")
    nbcu_synd_prelog_url = fields.Char(string="NBCU Synd Prelog URL")
    nhl_local_network_post_log_week = fields.Date(string="NHL Local Network PostLog Week")
    nhl_local_network_pre_log_week = fields.Date(string="NHL Local Network Prelog Week")
    nhl_network_post_log_week = fields.Date(string="NHL Network PostLog Week")
    nhl_network_pre_log_week = fields.Date(string="NHL Network Prelog Week")
    nhl_local_network_post_log_url = fields.Char(string="NHL Local Network Post Log URL")
    nhl_local_network_post_logs_date_time = fields.Datetime(string="NHL Local Network Post Logs Date/Time")
    nhl_local_network_pre_logs_date_time = fields.Datetime(string="NHL Local Network Pre Logs Date/Time")
    nhl_local_network_prelog_nw_url = fields.Char(string="NHL Local Network Prelog NW URL")
    nhl_local_network_prelog_url = fields.Char(string="NHL Local Network Prelog URL")
    nhl_local_network_query_postlogs = fields.Char(string="NHL Local Network Query Postlogs")
    nhl_local_network_query_prelogs_nw = fields.Char(string="NHL Local Network Query Prelogs NW")
    nhl_local_network_query_prelogs = fields.Char(string="NHL Local Network Query Prelogs")
    nhl_network_post_log_url = fields.Char(string="NHL Network Post Log URL")
    nhl_network_post_logs_date_time = fields.Datetime(string="NHL Network Post Logs Date/Time")
    nhl_network_pre_logs_date_time = fields.Datetime(string="NHL Network Pre Logs Date/Time")
    nhl_network_prelog_nw_url = fields.Char(string="NHL Network Prelog NW URL")
    nhl_network_prelog_url = fields.Char(string="NHL Network Prelog URL")
    nhl_network_query_postlogs = fields.Char(string="NHL Network Query Postlogs")
    nhl_network_query_prelogs_nw = fields.Char(string="NHL Network Query Prelogs NW")
    nhl_network_query_prelogs = fields.Char(string="NHL Network Query Prelogs")
    newsy_post_log_url = fields.Char(string="Newsy Post Log URL")
    newsy_post_logs_date_time = fields.Datetime(string="Newsy Post Logs Date/Time")
    newsy_pre_log_url = fields.Char(string="Newsy Pre Log URL")
    newsy_pre_logs_date_time = fields.Datetime(string="Newsy Pre Logs Date/Time")
    newsy_prelog_nw_url = fields.Char(string="Newsy Prelog NW URL")
    newsy_query_postlogs = fields.Char(string="Newsy Query Postlogs")
    newsy_query_prelogs_nw = fields.Char(string="Newsy Query Prelogs NW")
    newsy_query_prelogs = fields.Char(string="Newsy Query Prelogs")
    nosey_tv_post_log_week = fields.Date(string="NoseyTV Postlog Week")
    nosey_tv_pre_log_week = fields.Date(string="NoseyTV Prelog Week")
    nosey_tv_post_logs_date_time = fields.Datetime(string="NoseyTV Post Logs Date/Time")
    nosey_tv_postlog_url = fields.Char(string="NoseyTV Postlog URL")
    nosey_tv_pre_log_date_time = fields.Datetime(string="NoseyTV Pre Log Date/Time")
    nosey_tv_prelog_nw_url = fields.Char(string="NoseyTV Prelog NW URL")
    nosey_tv_prelog_url = fields.Char(string="NoseyTV Prelog URL")
    nosey_tv_query_postlog = fields.Char(string="NoseyTV Query Postlog")
    nosey_tv_query_prelog = fields.Char(string="NoseyTV Query Prelog")
    nosey_tv_query_prelogs_nw = fields.Char(string="NoseyTV Query Prelogs NW")
    novelisima_postlog_week_date_time = fields.Datetime(string="Novelisima Postlog Week Date/Time")
    novelisima_postlog_week = fields.Date(string="Novelisima Postlog Week")
    novelisima_prelog_week = fields.Date(string="Novelisima PrelogWeek")
    novelisima_prelog_date_time = fields.Datetime(string="Novelisima Prelog Date Time")
    novelisima_prelog_nw_url = fields.Char(string="Novelisima Prelog NW URL")
    novelisima_prelog_url = fields.Char(string="Novelisima Prelog URL")
    oak_ae = fields.Many2one('res.users', string="Oak AE", ondelete='set null')
    onyx_ae = fields.Many2one('res.users', string="Onyx AE", ondelete='set null')
    other_address = fields.Char(string="OtherAddress")
    other_phone = fields.Char(string="OtherPhone")
    outlaw_post_log_week = fields.Date(string="Outlaw PostLogWeek")
    outlaw_pre_log_week = fields.Date(string="Outlaw Prelog Week")
    outlaw_pp_postlog_url = fields.Char(string="Outlaw PP Postlog URL")
    outlaw_pp_postlog_week = fields.Date(string="Outlaw PP Postlog Week")
    outlaw_post_logs_date_time = fields.Datetime(string="Outlaw Post Logs Date/Time")
    outlaw_post_log_url = fields.Char(string="Outlaw Post log URL")
    outlaw_pre_logs_date_time = fields.Datetime(string="Outlaw Pre Logs Date/Time")
    outlaw_prelog_nw_url = fields.Char(string="Outlaw Prelog NW URL")
    outlaw_prelog_url = fields.Char(string="Outlaw Prelog URL")
    outlaw_query_postlogs = fields.Char(string="Outlaw Query Postlogs")
    outlaw_query_prelogs_nw = fields.Char(string="Outlaw Query Prelogs NW")
    outlaw_query_prelogs = fields.Char(string="Outlaw Query Prelogs")
    owner_id = fields.Many2one('res.partner', string="OwnerId", ondelete='set null')
    panther_ae = fields.Many2one('res.users', string="Panther AE", ondelete='set null')
    pine_ae = fields.Many2one('res.users', string="Pine AE", ondelete='set null')
    platinum_ae = fields.Many2one('res.users', string="Platinum AE", ondelete='set null')
    post_log_week = fields.Date(string="Post Log Week")
    pre_log_week = fields.Date(string="Pre Log Week")
    prelog_cc = fields.Char(string="Prelog Cc")
    pronouns = fields.Char(string="Pronouns")
    quest_network_post_log_week = fields.Date(string="Quest Network PostLog Week")
    quest_network_pre_log_week = fields.Date(string="Quest PreLog Week")
    quest_network_pre_logs_date_time = fields.Datetime(string="Quest Pre Logs Date/Time")
    quest_network_query_postlogs = fields.Char(string="Quest Network Query Postlogs")
    quest_network_query_prelogs_nw = fields.Char(string="Quest Network Query Prelogs NW")
    quest_network_query_prelogs = fields.Char(string="Quest Network Query Prelogs")
    quest_post_log = fields.Char(string="Quest Post Log URL")
    quest_post_logs_date_time = fields.Datetime(string="Quest Post Logs Date/Time")
    quest_pre_log_url = fields.Char(string="Quest Pre Log URL")
    quest_prelog_nw_url = fields.Char(string="Quest Prelog NW URL")
    reports_to_id = fields.Many2one('res.partner', string="ReportsToId", ondelete='set null')
    sd_lc = fields.Date(string="SD LC")
    sd_status = fields.Char(string="SD Status")
    sfss_dupe_catcher_override_dupe_catcher = fields.Boolean(string="Contact Override DupeCatcher", default=False)
    sf_lc = fields.Date(string="SF LC")
    sf_status = fields.Char(string="SF Status")
    scripps_news_post_log_week = fields.Date(string="Scripps News PostLog Week")
    scripps_news_pre_log_week = fields.Date(string="Scripps News PreLog Week")
    silver_ae = fields.Many2one('res.users', string="Silver AE", ondelete='set null')
    synd_post_log_query_url = fields.Char(string="Synd Post Log Query URL")
    synd_post_log_url = fields.Char(string="Synd Post Log URL")
    synd_pre_log_query_url = fields.Char(string="Synd Pre Log Query URL")
    synd_pre_log_url = fields.Char(string="Synd Pre Log URL")
    the365_post_log_week = fields.Date(string="THE365 PostLogWeek")
    the365_pre_log_week = fields.Date(string="THE365 Prelog Week")
    the365_pp_postlog_url = fields.Char(string="THE365 PP Postlog URL")
    the365_pp_postlog_week = fields.Date(string="THE365 PP Postlog Week")
    the365_post_logs_date_time = fields.Datetime(string="THE365 Post Logs Date/Time")
    the365_post_log_url = fields.Char(string="THE365 Post-log URL")
    the365_pre_logs_date_time = fields.Datetime(string="THE365 Pre Logs Date/Time")
    the365_prelog_nw_url = fields.Char(string="THE365 Prelog NW URL")
    the365_prelog_url = fields.Char(string="THE365 Prelog URL")
    the365_query_postlogs = fields.Char(string="THE365 Query Postlogs")
    the365_query_prelogs_nw = fields.Char(string="THE365 Query Prelogs NW")
    the365_query_prelogs = fields.Char(string="THE365 Query Prelogs")
    tl_lc = fields.Date(string="TL LC")
    tl_status = fields.Char(string="TL Status")
    tvg2_post_log_week = fields.Date(string="TVG2 PostLog Week")
    tvg2_pre_log_week = fields.Date(string="TVG2 PreLog Week")
    tvg_post_log_week = fields.Date(string="TVG PostLog Week")
    tvg_pre_log_week = fields.Date(string="TVG PreLog Week")
    twist_post_log_week = fields.Date(string="TWIST Postlog Week")
    twist_pre_log_week = fields.Date(string="TWIST Prelog Week")
    twist_prelog_nw_url = fields.Char(string="TWIST Prelog NW URL")
    teal_ae = fields.Many2one('res.users', string="Teal AE", ondelete='set null')
    this_tv_post_week = fields.Date(string="ThisTV Post Week")
    this_tv_pre_log_week = fields.Date(string="ThisTV PreLog Week")
    title_type = fields.Char(string="TitleType")
    traffic_cc = fields.Char(string="Traffic CC")
    traffic_contact = fields.Many2one('res.partner', string="[Dep]Traffic Contact", ondelete='set null')
    true_crime_network_post_log_week = fields.Date(string="True Crime Network PostLogWeek")
    true_crime_network_pre_log_week = fields.Date(string="True Crime Network PreLog Week")
    true_real_post_log_week = fields.Date(string="True Real Post Log Week")
    true_real_pre_log_week = fields.Date(string="True Real Pre Log Week")
    true_crime_network_post_date_time = fields.Datetime(string="True Crime Network Post Date/Time")
    true_crime_network_post_url = fields.Char(string="True Crime Network Post URL")
    true_crime_network_pre_date_time = fields.Datetime(string="True Crime Network Pre Date/Time")
    true_crime_network_prelog_nw = fields.Char(string="True Crime Network Prelog NW URL")
    true_crime_network_prelog_url = fields.Char(string="True Crime Network Prelog URL")
    true_crime_network_query_postlogs = fields.Char(string="True Crime Network Query Postlogs")
    true_crime_network_query_prelogs_nw = fields.Char(string="True Crime Network Query Prelogs NW")
    true_crime_network_query_prelogs = fields.Char(string="True Crime Network Query Prelogs")
    true_real_post_log_url = fields.Char(string="True Real Post Log URL")
    true_real_post_logs_date_time = fields.Datetime(string="True Real Post Logs Date Time")
    true_real_pre_logs_date_time = fields.Datetime(string="True Real Pre Logs Date Time")
    true_real_prelog_nw_url = fields.Char(string="True Real Prelog NW URL")
    true_real_query_post_logs = fields.Char(string="True Real Query Post Logs")
    true_real_query_pre_logs_nw = fields.Char(string="True Real Query Pre Logs NW")
    true_real_query_pre_logs = fields.Char(string="True Real Query Pre Logs")
    twist_pp_post_log_url = fields.Char(string="Twist PP Post Log URL")
    twist_pp_postlog_week = fields.Date(string="Twist PP Postlog Week")
    twist_post_logs_date_time = fields.Datetime(string="Twist Post Logs Date/Time")
    twist_pre_log_date_time = fields.Datetime(string="Twist Pre Log Date/Time")
    twist_query_postlogs = fields.Char(string="Twist Query Postlogs")
    twist_query_prelogs_nw = fields.Char(string="Twist Query Prelogs NW")
    twist_query_prelogs = fields.Char(string="Twist Query Prelogs")
    univision_synd_post_log_url = fields.Char(string="Univision Synd Post Log URL")
    univision_synd_pre_log_url = fields.Char(string="Univision Synd Pre Log URL")
    univision_synd_query_postlogs = fields.Char(string="Univision Synd Query Postlogs")
    univision_synd_query_prelogs = fields.Char(string="Univision Synd Query Prelogs")
    wapa_cinco_post_url = fields.Char(string="WAPA Cinco Post URL")
    wapa_cinco_postlog_week = fields.Date(string="WAPA Cinco Postlog Week")
    wapa_cinco_pre_log_week = fields.Date(string="WAPA Cinco PreLog Week")
    wapa_cinco_pre_nw_url = fields.Char(string="WAPA Cinco Pre NW URL")
    wapa_cinco_pre_tw_url = fields.Char(string="WAPA Cinco Pre TW URL")
    wapa_cinco_url = fields.Char(string="WAPA Cinco URL")
    wapa_post_date = fields.Date(string="WAPA Post Date")
    wapa_cinco_post_log_bundle = fields.Char(string="Wapa Cinco Post Log Bundle")
    wapa_cinco_post_log_spot = fields.Char(string="Wapa Cinco Post Log Spot")
    yellow_ae = fields.Many2one('res.users', string="Yellow AE", ondelete='set null')
    yellow_syndication_ae = fields.Many2one('res.users', string="Yellow Syndication AE", ondelete='set null')
    # === END SF parity fields ===

    # =================================================================== #
    # === SF parity fields (auto-generated, full Salesforce field set) === #
    # =================================================================== #
    account_source = fields.Char(string="AccountSource")
    account_count = fields.Integer(string="Account Count")
    account_type = fields.Selection([('Agency', 'Agency'), ('Network', 'Network'), ('Employee', 'Employee'), ('Vendor', 'Vendor'), ('1099', '1099')], string="Account Type")
    agency_approved_to_book = fields.Boolean(string="Agency Approved to Book", default=False)
    agency_log = fields.Boolean(string="Letter Of Guarantee", default=False)
    agency_status = fields.Selection([('Active', 'Active'), ('Hold', 'Hold'), ('Inactive', 'Inactive')], string="Agency Status")
    air_affidavit = fields.Char(string="Air Affidavit")
    annual_revenue = fields.Char(string="AnnualRevenue")
    balance = fields.Monetary(string="Balance", currency_field='currency_id')
    billing_address = fields.Char(string="BillingAddress")
    billing_contact = fields.Many2one('res.partner', string="Billing Contact", ondelete='set null')
    brand_color = fields.Text(string="Brand Color")
    cia_due_date = fields.Date(string="CIA Due Date")
    cia_invoice_url = fields.Char(string="CIA Invoice URL")
    cia_month = fields.Char(string="CIA Month")
    cia_notes = fields.Text(string="CIA Notes")
    cia = fields.Boolean(string="CIA", default=True)
    class_field = fields.Selection([('standard', 'Standard'), ('cobalt', 'Cobalt'), ('silver', 'Silver')], string="Class")
    credit_check = fields.Boolean(string="Credit Check", default=False)
    credit_risk = fields.Boolean(string="Credit Risk", default=False)
    emt_agency_codes_required = fields.Boolean(string="EMT Agency Codes Required", default=False)
    emt_code = fields.Char(string="EMT CODE")
    emerald_ae = fields.Many2one('res.users', string="Emerald AE", ondelete='set null')
    final_expense_total = fields.Monetary(string="FinalExpenseTotal", currency_field='currency_id')
    fire2 = fields.Many2one('res.users', string="Wolf AE (Contact)", ondelete='set null')
    green_ae = fields.Many2one('res.users', string="Green AE", ondelete='set null')
    hold_placed_on_agency_account = fields.Boolean(string="Hold Placed on Agency Account", default=True)
    inactive = fields.Boolean(string="Inactive", default=False)
    industry = fields.Char(string="Industry (SF)")
    intacct_id = fields.Char(string="Intacct Customer ID")
    intacct_credit_limit = fields.Monetary(string="Intacct Credit Limit", currency_field='currency_id')
    intacct_vendor_id = fields.Char(string="Intacct Vendor Id")
    invoice_date = fields.Char(string="Invoice Date")
    is_customer_portal = fields.Char(string="IsCustomerPortal")
    jade_ae = fields.Many2one('res.users', string="Jade AE", ondelete='set null')
    jigsaw = fields.Char(string="Jigsaw")
    log_w_expiration_date = fields.Date(string="Letter Of Guarantee w Expiration Date")
    last_account_activity = fields.Datetime(string="Last Account Activity")
    last_activity = fields.Date(string="Last Activity")
    last_lf_deal = fields.Date(string="Last LF Deal")
    last_sf_deal = fields.Date(string="Last SF Deal")
    lime_ae = fields.Many2one('res.users', string="Lime AE", ondelete='set null')
    maple_ae = fields.Many2one('res.users', string="Maple AE", ondelete='set null')
    marathon_commission_x = fields.Float(string="Agency Commission %")
    monitoring = fields.Boolean(string="Monitoring", default=False)
    netsuite_balance = fields.Monetary(string="Netsuite Balance", currency_field='currency_id')
    netsuite_customer_id = fields.Char(string="Netsuite Customer ID")
    netsuite_vendor_id = fields.Char(string="Netsuite Vendor ID")
    network_commission = fields.Float(string="Network Commission")
    nosey_performing_rights_license_comments = fields.Text(string="Nosey Performing Rights License Comments")
    nosey = fields.Boolean(string="Nosey Performing Rights Licenses", default=False)
    number_of_employees = fields.Char(string="NumberOfEmployees")
    oak_ae = fields.Many2one('res.users', string="Oak AE", ondelete='set null')
    onyx_ae = fields.Many2one('res.users', string="Onyx AE", ondelete='set null')
    operating_hours_id = fields.Many2one('res.partner', string="OperatingHoursId", ondelete='set null')
    owner_id = fields.Many2one('res.partner', string="OwnerId", ondelete='set null')
    ownership = fields.Char(string="Ownership")
    panther_ae = fields.Many2one('res.users', string="Panther AE", ondelete='set null')
    performing_rights_license_payment_terms = fields.Char(string="Performing Rights License Payment Terms")
    performing_rights_license_pymt_comments = fields.Text(string="Performing Rights License Pymt Comments")
    pine_ae = fields.Many2one('res.users', string="Pine AE", ondelete='set null')
    platinum_ae = fields.Many2one('res.users', string="Platinum AE", ondelete='set null')
    prelog_agency = fields.Char(string="Prelog Agency")
    primary_contact = fields.Many2one('res.partner', string="Primary Contact", ondelete='set null')
    qb_full_name = fields.Char(string="QB Full Name")
    rating = fields.Char(string="Rating")
    red_ae = fields.Many2one('res.users', string="Fire AE (Contact)", ondelete='set null')
    region = fields.Char(string="Region")
    sfss_dupe_catcher_override_dupe_catcher = fields.Boolean(string="Account Override DupeCatcher", default=False)
    shipping_address = fields.Char(string="ShippingAddress")
    sic = fields.Char(string="Sic")
    sic_desc = fields.Char(string="SicDesc")
    silver_ae = fields.Many2one('res.users', string="Silver AE", ondelete='set null')
    silver_team_accounts = fields.Char(string="Silver Team Accounts")
    site = fields.Char(string="Site")
    teal_ae = fields.Many2one('res.users', string="Teal AE", ondelete='set null')
    ticker_symbol = fields.Char(string="TickerSymbol")
    tier = fields.Char(string="Tier")
    weekly_billing = fields.Boolean(string="Weekly Billing", default=False)
    yellow_ae = fields.Many2one('res.users', string="Yellow AE", ondelete='set null')
    zaapit_hierarchy_level = fields.Integer(string="Hierarchy Level")
    sf_class = fields.Selection([('Standard', 'Standard'), ('Cobalt', 'Cobalt'), ('Silver', 'Silver')], string='Class (SF)')
    # === END SF parity fields ===

    @api.depends('deal_ids')
    def _compute_marathon_counts(self):
        for partner in self:
            partner.deal_count = len(partner.deal_ids)
